#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-AuthCookieNTLM
version:      0.07
version_from: lib/Apache/AuthCookieNTLM.pm
installdirs:  site
requires:
    Apache::Constants:             0.01
    Test::More:                    0.01
    Apache::AuthenNTLM:            2.07
    Apache::Cookie:                0.01
    Apache::Request:               0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
